version: '3.8'
services:
  kafka-topic-initialization:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
    entrypoint: [ "sh", "-c" ]
    command: |
      "
      # block until kafka is reachable
      kafka-topics --bootstrap-server kafka-broker-3:9092 --list
      echo -e 'Creating kafka topics.'
      kafka-topics --bootstrap-server kafka-broker-3:9092 --create --if-not-exists --topic ${KAFKA_TOPIC_TWITTER} --partitions 3 --replication-factor 3
      echo -e 'Following topics are available:'
      kafka-topics --bootstrap-server kafka-broker-3:9092 --list
      "
    networks:
      - ${GLOBAL_NETWORK:-kafka}
    volumes:
      - microservices-twitter-kafka-broker-initialization:${VOLUME_PATH}kafka-broker-3:/var/lib/kafka/data, /etc/kafka/secrets