spring:
  config:
    name: twitter-to-kafka-service

twitter-to-kafka-service:
  twitter-keywords:
    - Kotlin
    - Microservices
    - Kafka
    - Elasticsearch
    - Messi
  enable-feign-tweets: false
  enable-v2-tweets: true
  enable-mock-tweets: false
  twitter-base-url: https://api.twitter.com
  twitter-tweet-url: /2/tweets/search/stream?tweet.fields=created_at&expansions=author_id
  twitter-rules-url: /2/tweets/search/stream/rules
  twitter-bearer-token: ${TWITTER_BEARER_TOKEN}
  twitter-tweets-limit: 0
  common:
    app-start: App starts...
    info-message: Searched keywords

