spring:
  config:
    name: twitter-to-kafka-service

twitter-to-kafka-service:
  twitter-keywords:
    - Kotlin
    - Microservices
    - Kafka
    - Elasticsearch
    - USA
  enable-v2-tweets: true
  enable-mock-tweets: false
  twitter-v2-base-url: https://api.twitter.com/2/tweets/search/stream?tweet.fields=created_at&expansions=author_id
  twitter-v2-rules-base-url: https://api.twitter.com/2/tweets/search/stream/rules
  twitter-v2-bearer-token: ${TWITTER_BEARER_TOKEN}
  common:
    app-start: App starts...
    info-message: Searched keywords

