spring:
  config:
    name: twitter-to-kafka-service

twitter-to-kafka-service:
  twitter-keywords:
    - Kotlin
    - Microservices
    - Kafka
    - Elasticsearch
    - Messi
  enable-mock-tweets: false
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000
  enable-feign-tweets: true
  enable-v2-tweets: false
  twitter-base-url: https://api.twitter.com
  twitter-tweet-url: /2/tweets/search/stream?tweet.fields=created_at&expansions=author_id
  twitter-rules-url: /2/tweets/search/stream/rules
  twitter-bearer-token: ${TWITTER_BEARER_TOKEN}
  twitter-tweets-limit: 0
  common:
    app-start: App starts...
    info-message: Searched keywords

retry-configuration:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  max-attempts: 3
  sleep-time-ms: 2000

